[tool.basedpyright]
include = ["mappraiser/python"]
exclude = ["**/workflow/", "**/__pycache__"]

typeCheckingMode = "standard"

pythonVersion = "3.10"
pythonPlatform = "Linux"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = [
    # pycodestyle
    'E',
    # pyflakes
    'F',
    # pyupgrade
    'UP',
    # flake8-debugger
    'T10',
    # isort
    'I',
]

[tool.ruff.format]
quote-style = 'single'
