line-length = 100
target-version = "py310"

[lint]
select = [
    # pycodestyle
    'E',
    # pyflakes
    'F',
    # pyupgrade
    'UP',
    # flake8-debugger
    'T10',
]

[format]
quote-style = 'single'
