[tool.basedpyright]
include = ["mappraiser/python"]
exclude = ["**/workflow/", "**/__pycache__"]

typeCheckingMode = "standard"

pythonVersion = "3.10"
pythonPlatform = "Linux"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
extend-select = [
    "ARG",  # flake8-unused-arguments
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "E1",   # pycodestyle-indentation
    "EM",   # flake8-errmsg
    "EXE",  # flake8-executable
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "NPY",  # NumPy specific rules
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PL",   # pylint
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    "PYI",  # flake8-pyi
    "RET",  # flake8-return
    "RUF",  # Ruff-specific
    "SIM",  # flake8-simplify
    "T10",  # flake8-debugger
    "T20",  # flake8-print
    "UP",   # pyupgrade
    "YTT",  # flake8-2020
]
ignore = [
    "PLR09",   # Too many <...>
    "PLR2004", # Magic value used in comparison
]

[tool.ruff.lint.per-file-ignores]
"tests.py" = ["T201"]
"toast_so_sim.py" = ["E402", "PTH"]

[tool.ruff.format]
quote-style = 'single'
